<?php

return [
    'name' => 'GrowLead CRM',

    'industries' => [
        'generic' => 'Generic CRM',
        'real_estate' => 'Real Estate',
        'automotive' => 'Automotive',
        'education' => 'Education',
        'insurance' => 'Insurance',
        'solar' => 'Solar',
        'agency' => 'Agency',
        'saas' => 'SaaS',
        'other' => 'Other',
    ],

    'roles' => [
        'administrator',
        'manager',
        'team_lead',
        'agent',
        'viewer',
    ],

    'permissions' => [
        'dashboard.view',
        'leads.view',
        'leads.create',
        'leads.edit',
        'leads.delete',
        'leads.assign',
        'leads.export',
        'campaigns.view',
        'campaigns.create',
        'campaigns.edit',
        'campaigns.delete',
        'reports.view',
        'reports.export',
        'users.view',
        'users.create',
        'users.edit',
        'teams.manage',
        'automations.view',
        'automations.manage',
        'integrations.view',
        'integrations.manage',
        'settings.view',
        'settings.manage',
        'opportunities.view',
        'opportunities.manage',
        'ai.view',
    ],

    'default_pipeline_stages' => [
        ['name' => 'New Lead', 'slug' => 'new-lead', 'color' => '#2563EB', 'type' => 'open', 'probability' => 10],
        ['name' => 'Contacted', 'slug' => 'contacted', 'color' => '#0EA5E9', 'type' => 'open', 'probability' => 20],
        ['name' => 'Qualified', 'slug' => 'qualified', 'color' => '#8B5CF6', 'type' => 'open', 'probability' => 40],
        ['name' => 'Opportunity', 'slug' => 'opportunity', 'color' => '#F59E0B', 'type' => 'open', 'probability' => 55],
        ['name' => 'Proposal', 'slug' => 'proposal', 'color' => '#F97316', 'type' => 'open', 'probability' => 70],
        ['name' => 'Negotiation', 'slug' => 'negotiation', 'color' => '#EF4444', 'type' => 'open', 'probability' => 80],
        ['name' => 'Closed Won', 'slug' => 'closed-won', 'color' => '#16A34A', 'type' => 'won', 'probability' => 100],
        ['name' => 'Closed Lost', 'slug' => 'closed-lost', 'color' => '#64748B', 'type' => 'lost', 'probability' => 0],
    ],

    'default_lead_statuses' => [
        ['name' => 'Not Contacted', 'slug' => 'not_contacted', 'aliases' => ['new', 'new-lead', 'Not Contacted']],
        ['name' => 'Qualified', 'slug' => 'qualified', 'aliases' => ['Qualified']],
        ['name' => 'Working Deal', 'slug' => 'working_deal', 'aliases' => ['Working Deal', 'opportunity', 'proposal', 'negotiation']],
        ['name' => 'Deal Closed', 'slug' => 'deal_closed', 'aliases' => ['Deal Closed', 'won', 'closed-won', 'closed_won']],
        ['name' => 'Lost Deal', 'slug' => 'lost_deal', 'aliases' => ['Lost Deal', 'lost', 'closed-lost', 'closed_lost']],
        ['name' => 'Future Prospect', 'slug' => 'future_prospect', 'aliases' => ['Future Prospect']],
        ['name' => 'Did Not Respond', 'slug' => 'did_not_respond', 'aliases' => ['Did Not Respond']],
        ['name' => 'Unqualified', 'slug' => 'unqualified', 'aliases' => ['Unqualified']],
    ],

    'default_task_types' => [
        ['name' => 'Call', 'slug' => 'call'],
        ['name' => 'Email', 'slug' => 'email'],
        ['name' => 'WhatsApp', 'slug' => 'whatsapp'],
        ['name' => 'Text', 'slug' => 'text', 'aliases' => ['sms']],
        ['name' => 'Meeting', 'slug' => 'meeting'],
    ],

    'campaign_status_groups' => [
        'active' => ['active', 'running', 'live', 'draft'],
        'archived' => ['archived', 'completed', 'ended', 'inactive'],
        'paused' => ['paused', 'on_pause', 'pause', 'on pause'],
    ],

    'completed_task_statuses' => ['completed', 'cancelled', 'done'],

    'default_tags' => [
        ['name' => 'Hot Lead', 'color' => '#EF4444'],
        ['name' => 'High Intent', 'color' => '#16A34A'],
        ['name' => 'Decision Maker', 'color' => '#2563EB'],
        ['name' => 'Urgent', 'color' => '#F97316'],
        ['name' => 'Follow-up Required', 'color' => '#F59E0B'],
        ['name' => 'Demo Requested', 'color' => '#8B5CF6'],
        ['name' => 'Buy Soon', 'color' => '#0EA5E9'],
        ['name' => 'Interested', 'color' => '#EF4444'],
        ['name' => 'DHA & Clifton', 'color' => '#16A34A'],
        ['name' => 'Gulshan / Johar', 'color' => '#16A34A'],
        ['name' => 'PECHS, Bahadurabad', 'color' => '#16A34A'],
        ['name' => 'Tariq Road/ShaheedeMillet', 'color' => '#16A34A'],
        ['name' => 'Nazimabad/North Nazimabad', 'color' => '#16A34A'],
        ['name' => 'Federal B Area', 'color' => '#16A34A'],
        ['name' => 'Liaquatabad', 'color' => '#16A34A'],
        ['name' => 'Scheme 33/Gulzar-e-Hijri', 'color' => '#16A34A'],
        ['name' => 'Saadi Town', 'color' => '#16A34A'],
        ['name' => 'NIPA/University Road', 'color' => '#16A34A'],
        ['name' => 'Airport Area', 'color' => '#16A34A'],
        ['name' => 'Surjani Town/New Karachi', 'color' => '#16A34A'],
        ['name' => 'North Karachi / Nagan', 'color' => '#16A34A'],
        ['name' => 'Manghopir/SITE Area', 'color' => '#16A34A'],
        ['name' => 'Baldia Town/Orangi Town', 'color' => '#16A34A'],
        ['name' => 'Targeted Areas', 'color' => '#06B6D4'],
        ['name' => 'Saddar,Garden,Civil Lines', 'color' => '#16A34A'],
        ['name' => 'Frere Town/Bath Island', 'color' => '#16A34A'],
        ['name' => 'JamshedRoad/Soldier BazaR', 'color' => '#16A34A'],
        ['name' => 'OTHER AREA', 'color' => '#111827'],
        ['name' => 'Lead Visit Done', 'color' => '#EAB308'],
        ['name' => 'Interested In Plot', 'color' => '#64748B'],
        ['name' => 'Interested In Villa', 'color' => '#EF4444'],
    ],

    'default_sources' => [
        ['name' => 'Meta', 'slug' => 'meta', 'type' => 'ads'],
        ['name' => 'Instagram', 'slug' => 'instagram', 'type' => 'ads'],
        ['name' => 'TikTok', 'slug' => 'tiktok', 'type' => 'ads'],
        ['name' => 'Google', 'slug' => 'google', 'type' => 'ads'],
        ['name' => 'LinkedIn', 'slug' => 'linkedin', 'type' => 'ads'],
        ['name' => 'Website', 'slug' => 'website', 'type' => 'web'],
        ['name' => 'Web Form', 'slug' => 'web-form', 'type' => 'web'],
        ['name' => 'WhatsApp', 'slug' => 'whatsapp', 'type' => 'messaging'],
        ['name' => 'API', 'slug' => 'api', 'type' => 'api'],
        ['name' => 'Webhook', 'slug' => 'webhook', 'type' => 'api'],
        ['name' => 'CSV', 'slug' => 'csv', 'type' => 'import'],
        ['name' => 'Manual', 'slug' => 'manual', 'type' => 'manual'],
        ['name' => 'Referral', 'slug' => 'referral', 'type' => 'manual'],
        ['name' => 'Bayut', 'slug' => 'bayut', 'type' => 'listing'],
        ['name' => 'Dubizzle', 'slug' => 'dubizzle', 'type' => 'listing'],
        ['name' => 'Other', 'slug' => 'other', 'type' => 'other'],
    ],

    'currencies' => [
        'USD' => 'USD — US Dollar',
        'PKR' => 'PKR — Pakistani Rupee',
        'AED' => 'AED — UAE Dirham',
        'EUR' => 'EUR — Euro',
        'GBP' => 'GBP — British Pound',
        'INR' => 'INR — Indian Rupee',
        'SAR' => 'SAR — Saudi Riyal',
        'QAR' => 'QAR — Qatari Riyal',
        'KWD' => 'KWD — Kuwaiti Dinar',
        'BHD' => 'BHD — Bahraini Dinar',
        'OMR' => 'OMR — Omani Rial',
        'CAD' => 'CAD — Canadian Dollar',
        'AUD' => 'AUD — Australian Dollar',
        'CNY' => 'CNY — Chinese Yuan',
        'JPY' => 'JPY — Japanese Yen',
        'TRY' => 'TRY — Turkish Lira',
        'EGP' => 'EGP — Egyptian Pound',
        'BDT' => 'BDT — Bangladeshi Taka',
    ],

    'sla_minutes' => 15,

    'privacy_email' => env('PRIVACY_CONTACT_EMAIL', env('MAIL_FROM_ADDRESS', 'hello@campaignpilot.test')),
];
